package com.github.stephenwanjala.crspcalckmp.ui

import androidx.compose.ui.graphics.Color


val primaryLightHighContrast = Color(0xFF002F47)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004E72)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF00340E)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF225329)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF312746)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF4E4465)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF7F9FF)
val onBackgroundLightHighContrast = Color(0xFF181C20)
val surfaceLightHighContrast = Color(0xFFF7F9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDDE3EA)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF272D32)
val outlineVariantLightHighContrast = Color(0xFF444A50)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D3135)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF95CDF7)
val surfaceDimLightHighContrast = Color(0xFFB6B9BE)
val surfaceBrightLightHighContrast = Color(0xFFF7F9FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEEF1F6)
val surfaceContainerLightHighContrast = Color(0xFFE0E3E8)
val surfaceContainerHighLightHighContrast = Color(0xFFD1D5D9)
val surfaceContainerHighestLightHighContrast = Color(0xFFC3C7CC)



val primaryDarkHighContrast = Color(0xFFE4F2FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF91C9F3)
val onPrimaryContainerDarkHighContrast = Color(0xFF000D17)
val secondaryDarkHighContrast = Color(0xFFC6FEC4)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF9AD099)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F02)
val tertiaryDarkHighContrast = Color(0xFFF6ECFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFCABCE4)
val onTertiaryContainerDarkHighContrast = Color(0xFF0F0523)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF101417)
val onBackgroundDarkHighContrast = Color(0xFFE0E3E8)
val surfaceDarkHighContrast = Color(0xFF101417)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF41474D)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEBF0F8)
val outlineVariantDarkHighContrast = Color(0xFFBDC3CA)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE0E3E8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF004D70)
val surfaceDimDarkHighContrast = Color(0xFF101417)
val surfaceBrightDarkHighContrast = Color(0xFF4C5055)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C2024)
val surfaceContainerDarkHighContrast = Color(0xFF2D3135)
val surfaceContainerHighDarkHighContrast = Color(0xFF383C40)
val surfaceContainerHighestDarkHighContrast = Color(0xFF43474B)







